# @package _global_

environment:
  id: Gym-Grid/Gridworld-Quicksand-Distract-4x4-v0

experiment:
  training_steps: 10000
  testing_episodes: 100

agent:
  critic:
    lr:
      init_value: 0.5
      min_value: 0.5
    lr_visit:
      init_value: 0.5
      min_value: 0.5
