# @package _global_
algorithm:
  id: greedy

agent:
  critic:
    id: QTableCritic
    q0_visit_min: null
    q0_visit_max: null

  actor:
    id: EpsilonGreedy
    beta_bar: null
    eps:
      init_value: 0.0
      min_value: 0.0
