# @package _global_
algorithm:
  id: q_count

agent:
  critic:
    id: QTableCriticWithCountQ
    q0_min: 0.0
    q0_max: 0.0

  actor:
    id: EpsilonGreedyWithUCBQCount
    beta_bar: null
    eps:
      init_value: 1.0
      min_value: 0.0
